// import Icons
import "bootstrap-icons/font/bootstrap-icons.css";

// import bootstrap
import "bootstrap/dist/css/bootstrap.css";

// import glightbox
import "glightbox/dist/css/glightbox.css";

import type { Metadata } from "next";
import { Playfair_Display } from "next/font/google";
import "./globals.css";
import TopBar from "./components/TopBar";
import Header from "./components/Header";
import BackToTopBtn from "./components/BackToTopBtn";
import Footer from "./sections/Footer";

const playfair = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700", "800", "900" ]
});

export const metadata: Metadata = {
  title: "NextJS Restauarnt Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${playfair.variable} ${playfair.variable}`}>
        <TopBar />
        <Header />
        {children}
        <Footer />
        <BackToTopBtn />
      </body>
      {/*<script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-C6RzsynM9kWDrMNet87bh950GNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
      crossOrigin="anonymous"
      ></script>*/}
    </html>
  );
}
